import { dataLinksFloatingNavbar } from '@/components/constants/data-links'
import CustomCursor from '@/components/custom-cursor'
import Header from '@/components/header'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { FloatingNav } from '@/components/ui/floating-navbar'
import SmoothScrolling from '@/lib/SmoothScrolling'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={inter.className}>
        <SmoothScrolling>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <FloatingNav navItems={dataLinksFloatingNavbar} />
            <CustomCursor />
          </ThemeProvider>
        </SmoothScrolling>
      </body>
    </html>
  )
}
